import {test,expect} from '@playwright/test'
import {readFileSync,writeFileSync} from 'node:fs'
import ExcelJS from 'exceljs'
const fixtures=JSON.parse(readFileSync(process.env.TEST_FIXTURES||'/tmp/quolyn-test-accounts.json','utf8'))
test('real session, import, enquiry review, quote PDF and reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/auth/login');await page.waitForFunction(()=>document.documentElement.dataset.hydrated==='true');await expect(page.getByRole('heading',{name:'Welcome back.'})).toBeVisible()
 await page.getByLabel('Email address').fill(fixtures.users[0].email);await page.getByLabel('Password',{exact:true}).fill(fixtures.password);await page.getByRole('button',{name:'Sign in →'}).click()
 await expect(page.getByRole('heading',{name:'Let’s make your next quote count.'})).toBeVisible();await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.hydrated==='true');await expect(page.getByRole('heading',{name:'Let’s make your next quote count.'})).toBeVisible()
 await page.screenshot({path:'artifacts/dashboard.png',fullPage:true});await page.setViewportSize({width:900,height:1100});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.screenshot({path:'artifacts/tablet.png',fullPage:true});await page.setViewportSize({width:1440,height:1000})
 await page.locator('nav a[href="/catalogue"]').click();await page.getByRole('link',{name:'↑ Import catalogue'}).click()
 const workbook=new ExcelJS.Workbook();workbook.addWorksheet('Instructions').addRow(['Read the catalogue']);workbook.addWorksheet('Products').addRows([['sku','name','price','currency'],['XLSX-CHECK','Worksheet preview item','10.50','INR']]);await page.getByLabel('Catalogue file').setInputFiles({name:'preview.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(await workbook.xlsx.writeBuffer())});await page.getByRole('combobox').first().selectOption('Products');await expect(page.locator('table')).toContainText('Worksheet preview item');
 await page.getByLabel('Catalogue file').setInputFiles({name:'browser-test.csv',mimeType:'text/csv',buffer:Buffer.from('sku,name,price,price_unit,selling_unit,currency,tax_percent,coverage,coverage_unit\nBROWSER-TILE,Browser grey porcelain tile,1200,box,box,INR,18,2.4,m2\n')})
 await expect(page.locator('table')).toContainText('Browser grey porcelain tile');await expect(page.getByText('1 valid',{exact:true})).toBeVisible();await page.getByLabel('I reviewed the mapping and duplicate rule. Import valid rows only.').check();await page.getByRole('button',{name:'Confirm import',exact:true}).click();await expect(page.getByText(/Import complete|already completed/)).toBeVisible()
 await page.locator('nav a[href="/enquiries"]').click();await page.getByRole('link',{name:'＋ New enquiry'}).click();await page.getByLabel('Enquiry title').fill('Browser verified quotation '+Date.now());await page.getByRole('combobox').first().selectOption({label:'Oakline Interiors (fictional)'})
 await page.getByLabel('Original enquiry').fill('Please quote 100 m2 of BROWSER-TILE grey porcelain tile.');await page.getByRole('button',{name:'Create enquiry →'}).click();await page.getByRole('button',{name:'Analyse enquiry',exact:true}).click();await expect(page.locator('.line-card')).toHaveCount(1)
 const line=page.locator('.line-card').first();await line.getByLabel('Resolved: Confirm product requirements with customer').click();await line.getByLabel('Clarification / customer answer').fill('Customer confirms exact SKU, 100 m2, no accessories.');await line.getByLabel('Product search line 1').fill('BROWSER-TILE');await line.getByRole('button',{name:'Find products'}).click();await line.locator('.candidate').filter({hasText:'Browser grey porcelain tile'}).getByRole('button',{name:'Select suggestion →'}).click();await line.getByLabel('Line review state').selectOption('confirmed');await line.getByRole('button',{name:'Save line'}).click();await expect(page.getByText('Review saved',{exact:true})).toBeVisible();await page.screenshot({path:'artifacts/enquiry.png',fullPage:true})
 await page.getByRole('button',{name:'Create quotation draft →'}).click();await expect(page.getByRole('heading',{name:'Quotation lines',exact:true})).toBeVisible();await page.getByLabel('I reviewed quantity, units, price and tax').check();await page.getByRole('button',{name:'Save & recalculate'}).click();await expect(page.getByText('All required review checks passed on the saved quotation.')).toBeVisible();await page.getByRole('button',{name:'Mark ready',exact:true}).click();await expect(page.locator('.page-title .pill')).toHaveText('ready');await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.hydrated==='true');await expect(page.locator('.page-title .pill')).toHaveText('ready')
 await page.getByRole('button',{name:'Customer preview'}).click();await expect(page.locator('.customer-preview')).toContainText('₹56,498.40');await page.screenshot({path:'artifacts/quote.png',fullPage:true})
 const responsePromise=page.waitForResponse(r=>r.url().includes('/api/quotes/export'))
 await page.getByRole('button',{name:'↓ PDF',exact:true}).click();const response=await responsePromise;expect(response.status()).toBe(200);const result=await response.json();expect(result.url).toContain('/storage/v1/object/sign/quote-documents/')
 const pdf=await page.request.get(result.url);expect(pdf.status()).toBe(200);expect((await pdf.body()).subarray(0,4).toString()).toBe('%PDF');writeFileSync('artifacts/browser-export.pdf',await pdf.body());
 const csvResponsePromise=page.waitForResponse(r=>r.url().includes('/api/quotes/export'));await page.getByRole('button',{name:'↓ CSV',exact:true}).click();const csvResponse=await csvResponsePromise;expect(csvResponse.status()).toBe(200);const csv=await page.request.get((await csvResponse.json()).url);expect(csv.status()).toBe(200);const csvText=await csv.text();expect(csvText).toContain('5649840');expect(csvText).not.toMatch(/cost_minor|margin_minor|internal_notes/);await expect(page.getByRole('heading',{name:'Saved documents'})).toBeVisible()
 await page.locator('nav a[href="/customers"]').click();await expect(page.getByRole('heading',{name:'Customers',exact:true})).toBeVisible();await page.locator('nav a[href="/settings"]').click();await expect(page.getByRole('heading',{name:'Settings',exact:true})).toBeVisible()
 expect(errors).toEqual([])
})
test('anonymous protected routes and export denied',async({page})=>{await page.goto('/quotes');await expect(page).toHaveURL(/auth\/login/);const r=await page.request.post('/api/quotes/export',{data:{id:crypto.randomUUID(),version:1,format:'pdf'}});expect(r.status()).toBe(401)})
