import {createClient} from '@supabase/supabase-js'
import {readFileSync,writeFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const fixtures=JSON.parse(readFileSync(process.env.TEST_FIXTURES||'/tmp/quolyn-test-accounts.json','utf8'))
const url=process.env.TEST_SUPABASE_URL||process.env.NUXT_PUBLIC_SUPABASE_URL!,key=process.env.TEST_SUPABASE_ANON_KEY||process.env.NUXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!
const clients=fixtures.users.map(()=>createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}))
const [a,b]=clients,anon=createClient(url,key,{auth:{persistSession:false}})
let checks=0
function ok(r:any){if(r.error)throw new Error(r.error.message);return r.data}
async function deny(label:string,action:PromiseLike<any>){const r=await action;assert(r.error||!r.data||r.data.length===0,label+' must fail or return no rows');console.log('PASS',label);checks++}
async function pass(label:string,fn:()=>Promise<void>){await fn();console.log('PASS',label);checks++}
for(let i=0;i<2;i++)ok(await clients[i].auth.signInWithPassword({email:fixtures.users[i].email,password:fixtures.password}))
const wa=ok(await a.rpc('create_workspace',{p_name:'Quolyn isolation test A'})),wb=ok(await b.rpc('create_workspace',{p_name:'Quolyn isolation test B'}))
ok(await a.from('quolyn_workspaces').update({name:'Northfield Surfaces (fictional)',address:'14 Example Road, Demo City',currency:'INR'}).eq('id',wa))
const product=ok(await a.from('quolyn_products').insert({workspace_id:wa,sku:'TEST-'+Date.now(),name:'Grey porcelain tile',price_unit:'box',selling_unit:'box',price_minor:120000,coverage:2.4,coverage_unit:'m2',currency:'INR',tax_bps:1800,attributes:{colour:'grey',material:'porcelain'}}).select().single())
const cust=ok(await a.from('quolyn_customers').insert({workspace_id:wa,name:'Oakline Interiors (fictional)',address:'12 Sample Lane',currency:'INR',discount_bps:500}).select().single())
await pass('own workspace read',async()=>assert.equal(ok(await a.from('quolyn_products').select('id').eq('id',product.id)).length,1))
await deny('other workspace read',b.from('quolyn_products').select('*').eq('id',product.id))
await deny('anonymous application read',anon.from('quolyn_products').select('*'))
await deny('cross workspace insert',b.from('quolyn_products').insert({workspace_id:wa,name:'Intrusion'}).select())
await deny('membership self-promotion',b.from('quolyn_workspace_members').insert({workspace_id:wa,user_id:fixtures.users[1].id,role:'owner'}).select())
await deny('membership update',a.from('quolyn_workspace_members').update({role:'member'}).eq('workspace_id',wa).select())
await deny('workspace reassignment',a.from('quolyn_products').update({workspace_id:wb}).eq('id',product.id).select())
await deny('cross workspace foreign key',b.from('quolyn_enquiries').insert({workspace_id:wb,customer_id:cust.id,title:'Invalid',source:'other',original_text:'test'}).select())
await deny('audit insertion',a.from('quolyn_activity_logs').insert({workspace_id:wa,event:'fake'}).select())
await deny('audit deletion',a.from('quolyn_activity_logs').delete().eq('workspace_id',wa).select())
const request=crypto.randomUUID(),payload={request_id:request,customer_id:cust.id,lines:[{product_id:product.id,description:'Grey porcelain tile',quantity:'100',unit:'m2',reviewed:true,requirements_resolved:true,included:true}]}
const qid=ok(await a.rpc('save_quote',{w:wa,p:payload}));let q=ok(await a.from('quolyn_quotes').select('*').eq('id',qid).single())
await pass('authoritative pack pricing',async()=>{assert.equal(q.total_minor,5649840);assert.equal(q.snapshot.lines[0].packs,'42');assert.equal(q.snapshot.lines[0].delivered,'100.8')})
await pass('safe create retry',async()=>assert.equal(ok(await a.rpc('save_quote',{w:wa,p:payload})),qid))
await deny('direct quote totals tampering',a.from('quolyn_quotes').update({total_minor:1}).eq('id',qid).select())
await deny('direct quote-line tampering',a.from('quolyn_quote_lines').update({price_minor:1}).eq('quote_id',qid).select())
await deny('cross workspace quote access',b.rpc('save_quote',{w:wa,p:payload}))
ok(await a.rpc('transition_quote',{w:wa,q:qid,v:q.version,target:'ready'}));q=ok(await a.from('quolyn_quotes').select('*').eq('id',qid).single())
await pass('ready invalidation after edit',async()=>{ok(await a.rpc('save_quote',{w:wa,p:{...payload,id:qid,version:q.version,request_id:crypto.randomUUID(),notes:'New terms'}}));q=ok(await a.from('quolyn_quotes').select('*').eq('id',qid).single());assert.equal(q.status,'needs review')})
await deny('optimistic concurrency stale edit',a.rpc('save_quote',{w:wa,p:{...payload,id:qid,version:1,request_id:crypto.randomUUID()}}))
ok(await a.rpc('transition_quote',{w:wa,q:qid,v:q.version,target:'ready'}));q=ok(await a.from('quolyn_quotes').select('*').eq('id',qid).single());ok(await a.rpc('transition_quote',{w:wa,q:qid,v:q.version,target:'sent'}));q=ok(await a.from('quolyn_quotes').select('*').eq('id',qid).single())
await pass('sent snapshot survives catalogue changes',async()=>{ok(await a.from('quolyn_products').update({price_minor:999999}).eq('id',product.id));const after=ok(await a.from('quolyn_quotes').select('*').eq('id',qid).single());assert.deepEqual(after.snapshot,q.snapshot)})
await pass('sent edit creates linked revision',async()=>{const id=ok(await a.rpc('save_quote',{w:wa,p:{...payload,id:qid,version:q.version,request_id:crypto.randomUUID()}}));assert.notEqual(id,qid);const revision=ok(await a.from('quolyn_quotes').select('*').eq('id',id).single());assert.equal(revision.parent_id,qid);assert.equal(revision.revision,2);assert.equal(revision.status,'needs review')})
await pass('atomic numbering under concurrency',async()=>{const ids=await Promise.all(Array.from({length:6},()=>a.rpc('save_quote',{w:wa,p:{...payload,request_id:crypto.randomUUID()}}).then(ok)));const rows=ok(await a.from('quolyn_quotes').select('number').in('id',ids));assert.equal(new Set(rows.map((r:any)=>r.number)).size,6)})
const path=`${wa}/${crypto.randomUUID()}.csv`;ok(await a.storage.from('catalogue-imports').upload(path,'sku,name\nA,Test',{contentType:'text/csv'}))
await pass('own private file',async()=>assert(ok(await a.storage.from('catalogue-imports').download(path))))
await deny('other workspace private file',b.storage.from('catalogue-imports').download(path))
await deny('anonymous private file',anon.storage.from('catalogue-imports').download(path))
await deny('foreign path upload',b.storage.from('catalogue-imports').upload(`${wa}/bad.csv`,'x',{contentType:'text/csv'}))
await pass('exact SKU matching',async()=>assert.equal(ok(await a.rpc('search_products',{w:wa,q:product.sku}))[0].id,product.id))
ok(await a.from('quolyn_product_aliases').insert({workspace_id:wa,product_id:product.id,alias:'grey sample alias '+product.sku}))
await pass('alias matching',async()=>assert.equal(ok(await a.rpc('search_products',{w:wa,q:'grey sample alias '+product.sku}))[0].id,product.id))
await pass('fuzzy matching',async()=>assert(ok(await a.rpc('search_products',{w:wa,q:'Grey porcelan'})).some((p:any)=>p.id===product.id)))
const enquiry=ok(await a.from('quolyn_enquiries').insert({workspace_id:wa,customer_id:cust.id,title:'Analysis verification',original_text:'Please quote 100 m2 grey tiles. Include underlay and matching edge trims. Delivery next month.',source:'email'}).select().single())
await pass('authenticated deterministic Edge Function',async()=>{const r=await a.functions.invoke('analyse-enquiry',{body:{workspace_id:wa,enquiry_id:enquiry.id}});const d=ok(r);assert.equal(d.mode,'deterministic');assert(d.result.lines.some((l:any)=>l.quantity===null));assert(d.result.notes.some((n:string)=>n.includes('Clarify')))})
await deny('anonymous Edge Function',anon.functions.invoke('analyse-enquiry',{body:{workspace_id:wa,enquiry_id:enquiry.id}}))
await deny('unconfigured provider preserves enquiry',a.functions.invoke('analyse-enquiry',{body:{workspace_id:wa,enquiry_id:enquiry.id,mode:'ai'}}))
await deny('missing version cannot bypass conflict check',a.rpc('save_quote',{w:wa,p:{...payload,id:qid,request_id:crypto.randomUUID()}}))
await deny('anonymous workspace creation',anon.rpc('create_workspace',{p_name:'No access'}))
await deny('cross workspace line product reference',b.from('quolyn_enquiry_lines').insert({workspace_id:wb,enquiry_id:enquiry.id,product_id:product.id,description:'Invalid'}).select())
await pass('unreviewed draft has no final total and cannot be ready',async()=>{const id=ok(await a.rpc('save_quote',{w:wa,p:{...payload,request_id:crypto.randomUUID(),lines:[{...payload.lines[0],reviewed:false}]}}));const draft=ok(await a.from('quolyn_quotes').select('*').eq('id',id).single());assert.equal(draft.total_minor,null);assert((await a.rpc('transition_quote',{w:wa,q:id,v:draft.version,target:'ready'})).error)})
await pass('manual fractional quantity and half-up tax',async()=>{const id=ok(await a.rpc('save_quote',{w:wa,p:{customer_id:cust.id,request_id:crypto.randomUUID(),lines:[{description:'Manual fractional item',quantity:'0.5',unit:'each',price_unit:'each',price_minor:'101',discount_bps:0,tax_bps:1000,reviewed:true,requirements_resolved:true}]}}));const r=ok(await a.from('quolyn_quotes').select('*').eq('id',id).single());assert.equal(r.total_minor,56)})
await pass('alternatives stay outside total',async()=>{const id=ok(await a.rpc('save_quote',{w:wa,p:{customer_id:cust.id,request_id:crypto.randomUUID(),lines:[{description:'Included',quantity:'1',unit:'each',price_unit:'each',price_minor:'100',discount_bps:0,tax_bps:0,reviewed:true,requirements_resolved:true},{description:'Alternative',included:false}]}}));assert.equal(ok(await a.from('quolyn_quotes').select('*').eq('id',id).single()).total_minor,100)})
await pass('manual discount replaces default under price override',async()=>{const id=ok(await a.rpc('save_quote',{w:wa,p:{...payload,request_id:crypto.randomUUID(),lines:[{...payload.lines[0],override_minor:'100000',override_reason:'Approved pilot pricing',discount_bps:1000}]}}));const r=ok(await a.from('quolyn_quotes').select('*').eq('id',id).single());assert.equal(r.snapshot.lines[0].net_minor,'3780000');assert.equal(r.snapshot.lines[0].discount_bps,1000)})
await pass('override without reason blocks readiness',async()=>{const id=ok(await a.rpc('save_quote',{w:wa,p:{...payload,request_id:crypto.randomUUID(),lines:[{...payload.lines[0],override_minor:'100000'}]}}));assert.equal(ok(await a.from('quolyn_quotes').select('*').eq('id',id).single()).total_minor,null)})
await pass('catalogue missing price cannot be supplied without explicit override',async()=>{const missing=ok(await a.from('quolyn_products').insert({workspace_id:wa,name:'Missing price',price_minor:null,tax_bps:0}).select().single());const id=ok(await a.rpc('save_quote',{w:wa,p:{customer_id:cust.id,request_id:crypto.randomUUID(),lines:[{product_id:missing.id,description:'Missing',quantity:'1',unit:'each',price_minor:'500',reviewed:true,requirements_resolved:true}]}}));assert.equal(ok(await a.from('quolyn_quotes').select('*').eq('id',id).single()).total_minor,null)})
await pass('sent revision retry is safe',async()=>{const req=crypto.randomUUID(),p={...payload,id:qid,version:q.version,request_id:req};const first=ok(await a.rpc('save_quote',{w:wa,p}));assert.equal(ok(await a.rpc('save_quote',{w:wa,p})),first)})
writeFileSync('artifacts/integration-fixture.json',JSON.stringify({workspace:wa,quote:qid,product:product.id,customer:cust.id,enquiry:enquiry.id}))
writeFileSync('artifacts/verified-quote.json',JSON.stringify(q,null,2))
console.log(`${checks} integration checks passed against ${url}`)
