<script setup lang="ts">
import {importFields,validateImport} from '#shared/utils/import'
import {safeCsv} from '#shared/utils/csv'
const db=useDb(),w=useWorkspace(),{error,busy,notice,run}=useAction(),file=ref<File|null>(null),sheets=ref<Record<string,string[][]>>({}),sheet=ref(''),mapping=ref<Record<string,string>>({}),duplicate=ref('skip'),progress=ref(0),confirmed=ref(false),importId=ref(''),ids=ref<string[]>([])
const headers=computed(()=>sheets.value[sheet.value]?.[0]||[])
const checked=computed(()=>validateImport((sheets.value[sheet.value]?.slice(1)||[]).map(row=>Object.fromEntries(importFields.map(f=>[f,row[headers.value.indexOf(mapping.value[f]||'')]||'']))),w.value!.currency))
const valid=computed(()=>checked.value.filter(r=>!r.errors.length)),rejected=computed(()=>checked.value.filter(r=>r.errors.length))
watch(sheet,()=>{mapping.value=Object.fromEntries(importFields.map(f=>[f,headers.value.find(h=>h.toLowerCase().trim()===f)||'']));ids.value=[];confirmed.value=false})
async function preview(e:Event){await run(async()=>{file.value=(e.target as HTMLInputElement).files?.[0]||null;if(!file.value)return;const body=new FormData();body.append('file',file.value);const r=await $fetch('/api/catalogue/preview',{method:'POST',body});sheets.value=r.sheets;sheet.value=Object.keys(r.sheets)[0]||'';importId.value=crypto.randomUUID();progress.value=0})}
function download(){const text=safeCsv(checked.value.map(r=>({row:r.row,errors:r.errors.join('; '),warnings:r.warnings.join('; ')})));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='import-report.csv';a.click();URL.revokeObjectURL(a.href)}
async function stableId(text:string){const h=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(b=>b.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-4${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`}
async function commit(){await run(async()=>{
 if(!confirmed.value||!file.value||!valid.value.length)throw new Error('Review and confirm the import first')
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.value.arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('')
 importId.value=await stableId(w.value!.id+hash+sheet.value+JSON.stringify(mapping.value)+duplicate.value)
 const path=`${w.value!.id}/${importId.value}/${file.value.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`
 const prior=check(await db.from('quolyn_catalogue_imports').select('*').eq('id',importId.value).maybeSingle())
 if(prior?.state==='complete'){progress.value=valid.value.length;notice.value='This exact import already completed. No duplicate products were created.';return}
 if(!prior){const upload=await db.storage.from('catalogue-imports').upload(path,file.value,{contentType:file.value.name.endsWith('.csv')?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});if(upload.error&&!upload.error.message.toLowerCase().includes('already exists'))throw upload.error;check(await db.from('quolyn_catalogue_imports').insert({id:importId.value,workspace_id:w.value!.id,file_path:path,state:'processing'}))}
 let skipped=prior?.summary?.skipped||0
 progress.value=prior?.summary?.processed||0
 for(let i=progress.value;i<valid.value.length;i+=50){
 const batch=valid.value.slice(i,i+50),skus=batch.map(r=>r.product.sku).filter((x):x is string=>!!x)
 const existing=skus.length?check(await db.from('quolyn_products').select('id,sku').eq('workspace_id',w.value!.id).in('sku',skus)):[]
 const rows:any[]=[],aliasRows:any[]=[]
 for(const row of batch){const found=existing.find(p=>p.sku===row.product.sku);if(found&&duplicate.value==='skip'){skipped++;continue}const id=found?.id||await stableId(importId.value+':'+row.row);rows.push({...row.product,id,workspace_id:w.value!.id,source:'import:'+importId.value});row.aliases.forEach(alias=>aliasRows.push({workspace_id:w.value!.id,product_id:id,alias}))}
 if(rows.length)check(await db.from('quolyn_products').upsert(rows,{onConflict:'id'}))
 if(aliasRows.length)check(await db.from('quolyn_product_aliases').upsert(aliasRows,{onConflict:'workspace_id,product_id,alias',ignoreDuplicates:true}))
 progress.value=Math.min(i+50,valid.value.length)
 check(await db.from('quolyn_catalogue_imports').update({summary:{processed:progress.value,skipped,rejected:rejected.value.length}}).eq('id',importId.value))
 }
 check(await db.from('quolyn_catalogue_imports').update({state:'complete',summary:{processed:progress.value,valid:valid.value.length,rejected:rejected.value.length,skipped}}).eq('id',importId.value));notice.value=`Import complete. ${progress.value} rows processed; ${skipped} existing SKUs skipped. ${rejected.value.length} rows rejected.`
})}

</script>
<template><div><div class="page-title"><div><div class="eyebrow">CATALOGUE / IMPORT</div><h1>Bring your products into focus.</h1><p>Preview, map and check your file before anything is imported.</p></div><a class="secondary" href="/sample-catalogue.csv" download>↓ Sample template</a></div><div class="panel"><div class="row between"><h2>1. Choose your spreadsheet</h2><span class="pill">CSV or XLSX · up to 10 MB</span></div><label>Catalogue file<input type="file" accept=".csv,.xlsx" @change="preview"></label><p class="muted">Decimal point prices only, no thousands separators. Formulas and macros are rejected. Up to 10,000 products.</p><p v-if="error" class="alert error" role="alert">{{error}}</p><p v-if="notice" class="alert success">{{notice}}</p></div><template v-if="headers.length"><div class="panel"><h2>2. Map columns</h2><label>Worksheet<select v-model="sheet"><option v-for="s in Object.keys(sheets)" :key="s">{{s}}</option></select></label><div class="form-grid"><label v-for="field in importFields" :key="field">{{field.replaceAll('_',' ')}}<select v-model="mapping[field]"><option value="">Not provided</option><option v-for="h in headers" :key="h">{{h}}</option></select></label></div></div><div class="panel"><div class="row between"><h2>3. Review and import</h2><button class="link" @click="download">Download error report ↓</button></div><div class="row"><span class="pill confirmed">{{valid.length}} valid</span><span class="pill warning">{{checked.filter(r=>r.warnings.length).length}} with warnings</span><span class="pill rejected">{{rejected.length}} rejected</span></div><div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>ROW</th><th>SKU / PRODUCT</th><th>RESULT</th></tr></thead><tbody><tr v-for="r in checked.slice(0,20)" :key="r.row"><td>{{r.row}}</td><td>{{r.product.name}}<small>{{r.product.sku||'Generated ID'}}</small></td><td style="white-space:normal">{{r.errors.join('; ')||r.warnings.join('; ')||'Ready to import'}}</td></tr></tbody></table></div><p class="muted">Showing the first 20 rows.</p><label>Existing SKU handling<select v-model="duplicate"><option value="skip">Skip existing SKUs</option><option value="replace">Replace existing product fields explicitly</option></select></label><label><input v-model="confirmed" type="checkbox">I reviewed the mapping and duplicate rule. Import valid rows only.</label><div class="row"><button class="primary" :disabled="busy||!confirmed||progress===valid.length" @click="commit">{{busy?'Importing…':'Confirm import'}}</button><span class="muted">{{progress}} / {{valid.length}} processed</span></div></div></template></div></template>
