<script setup lang="ts">
const db=useDb(),w=useWorkspace()
const {data,pending,error}=await useAsyncData('dashboard',async()=>{
 const results=await Promise.all([db.from('quolyn_enquiries').select('id,title,created_at,quolyn_customers(name),quolyn_enquiry_lines(state)').eq('workspace_id',w.value!.id).order('created_at',{ascending:false}).limit(20),db.from('quolyn_quotes').select('id,status').eq('workspace_id',w.value!.id),db.from('quolyn_enquiry_lines').select('id',{count:'exact',head:true}).eq('workspace_id',w.value!.id).not('state','in','(confirmed,excluded)')]);results.forEach(check)
 return {enquiries:results[0]!.data??[],quotes:results[1]!.data??[],unresolved:results[2]!.count??0}
})
const stats=computed(()=>[{label:'Recent enquiries',value:data.value?.enquiries.length??0,foot:'Latest 20 enquiries',icon:'↙'},{label:'Unresolved lines',value:data.value?.unresolved??0,foot:'Need your attention',icon:'◷'},{label:'Draft quotes',value:data.value?.quotes.filter(q=>['draft','needs review'].includes(q.status)).length??0,foot:'Work in progress',icon:'▤'},{label:'Ready to share',value:data.value?.quotes.filter(q=>q.status==='ready').length??0,foot:'Reviewed quotations',icon:'✓'}])
</script>
<template><div><div class="page-title"><div><div class="eyebrow">YOUR WORK AT A GLANCE</div><h1>Let’s make your next quote count.</h1><p>A clear view of enquiries, decisions and quotations.</p></div><NuxtLink class="primary" to="/enquiries/new">＋ New enquiry</NuxtLink></div><p v-if="error" class="alert error">{{error.message}}</p><div v-if="pending" class="loading">Loading your workspace…</div><template v-else><div class="stats"><div v-for="s in stats" :key="s.label" class="stat"><div class="stat-label">{{s.label}}<span class="stat-icon">{{s.icon}}</span></div><b>{{s.value}}</b><small>{{s.foot}}</small></div></div><div class="dashboard-grid"><div><div class="row between" style="margin-bottom:15px"><h2>Recent enquiries <span class="badge-count">{{data?.enquiries.length}}</span></h2><NuxtLink class="link" to="/enquiries">View all →</NuxtLink></div><div class="table-wrap"><table v-if="data?.enquiries.length"><thead><tr><th>ENQUIRY</th><th>REVIEW</th><th>RECEIVED</th></tr></thead><tbody><tr v-for="e in data.enquiries" :key="e.id"><td><NuxtLink :to="'/enquiries/'+e.id" class="table-link">{{e.title}}</NuxtLink><small>{{(e.quolyn_customers as any)?.name||'Customer not assigned'}}</small></td><td><span class="pill">{{e.quolyn_enquiry_lines.filter((l:any)=>['confirmed','excluded'].includes(l.state)).length}} / {{e.quolyn_enquiry_lines.length}} reviewed</span></td><td>{{new Date(e.created_at).toLocaleDateString()}}</td></tr></tbody></table><div v-else class="empty"><div class="empty-icon">↙</div><h3>A new enquiry starts here</h3><p>Paste a customer’s request and work through the details.</p><NuxtLink to="/enquiries/new" class="secondary">Create your first enquiry →</NuxtLink></div></div><div class="panel" style="margin-top:24px"><ActivityLog /></div></div><div class="panel"><span class="eyebrow">A SIMPLE WORKFLOW</span><h2 style="margin-top:12px">From request to ready.</h2><p class="muted" style="font-size:12px">Three steps. Your judgement at every one.</p><div class="steps"><NuxtLink to="/catalogue" class="step"><b>1</b><div><h3>Bring in your catalogue</h3><p>Products, prices and specifications in one place.</p></div></NuxtLink><NuxtLink to="/enquiries/new" class="step"><b>2</b><div><h3>Review the requirements</h3><p>Match products. Resolve what’s missing.</p></div></NuxtLink><NuxtLink to="/quotes" class="step"><b>3</b><div><h3>Prepare a checked quote</h3><p>Confirm the details and export a clear PDF.</p></div></NuxtLink></div><div class="alert warning" style="margin-top:28px">Suggestions assist. You make the final decision.</div></div></div></template></div></template>
